### ISSUE TITLE
Misc ToDo

### ISSUE THREAD

**Issue by KalinuxYT** [KalinuxYT/MinaCardsMod#10]
- [ ] Common Box Design
- [ ] Rare Box Design
- [ ] Epic Box Design
- [ ] Legendary Box Design

----------------------------------------------

- [ ] Destiny Common Pack Design
- [ ] Destiny Common Box Design
- [ ] Destiny Rare Pack Design
- [ ] Destiny Rare Box Design
- [ ] Destiny Epic Pack Design
- [ ] Destiny Epic Box Design
- [ ] Destiny Legendary Pack Design
- [ ] Destiny Legendary Box Design

----------------------------------------------

- [ ] Destiny Fire Deck Design
- [ ] Destiny Water Deck Design
- [ ] Destiny Earth Deck Design
- [ ] Destiny Air Deck Design

----------------------------------------------

- [x] Fantasy Pack Design
- [x] Cats Pack Design
- [x] Megabot Pack Design
- [x] Ghost Pack Design

----------------------------------------------

- [x] Ghost Card Background Design

----------------------------------------------

- [x] Standard Card Sleeves Design
- [x] Fire Card Sleeves Rework & Render
- [x] Water Card Sleeves Rework & Render
- [x] Earth Card Sleeves Rework & Render
- [x] Air Card Sleeves Rework & Render

----------------------------------------------

- [x] Deck Box Red Design
- [x] Deck Box Blue Design
- [x] Deck Box Green Design
- [x] Deck Box Yellow Design

----------------------------------------------

- [x] Collection Book Design
- [x] Premium Collection Book Design

----------------------------------------------

- [x] Playmat Design (x15)

----------------------------------------------

- [x] Comic Book Design (x9)

----------------------------------------------

- [ ] Dice Container Mesh & Design (x4)

----------------------------------------------

- [ ] Plushies & Figurines Mesh & Design (Tracked by #9)

----------------------------------------------

- [x] Change the phone service provider text
- [x] Change MY DIY icon
- [x] Change Review star icons

----------------------------------------------

- [ ] Change Food Mart textures

----------------------------------------------

- [x] Open/Closed Sign Design

----------------------------------------------

- [x] Pedestrian Sign Design
- [x] Parking Sign Design

**Comment by KalinuxYT** [comment]
- [ ] Investigate the modification of prices
- [ ] Investigate addition of celebration at certain card values
